backend:
  name: github
  repo: RedDev765/ecole-integrale-agadir
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "actualites"
    label: "ActualitÃ©s"
    label_singular: "ActualitÃ©"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date de publication", name: "date", widget: "datetime" }
      - { label: "Image Ã  la une", name: "image", widget: "image", required: false }
      - { label: "RÃ©sumÃ©", name: "description", widget: "text" }
      - { label: "Contenu", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - name: "accueil"
        label: "Page d'accueil"
        file: "src/pages/index.html"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Contenu", name: "body", widget: "hidden", default: "" }

  - name: "documents"
    label: "Documents"
    label_singular: "Document"
    folder: "downloads"
    create: true
    extension: "pdf"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Fichier", name: "file", widget: "file" }
